spring:
  application:
    name: GetABeer_REBUILD
  profiles:
    active: local
    include: 'oauth'
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: localhost
      port: 27017
      database: getABeer
  redis:
    host: localhost
    port: 6379
  jackson:
    time-zone: Asia/Seoul
  rsocket:
    server:
      transport: tcp
      port: 7070
    client:
      transport: tcp
      address: rsocket://localhost:7070

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.underbell: DEBUG

springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      key-length: 256

userId:
  admin: admin
mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: ThisIsSecretKeyForJWTForGetABeerREBUILDWithHS512SignatureAlgorithm
  access-token-expiration-minutes: 28800
  refresh-token-expiration-minutes: 1440