spring:
  profiles:
    active: local
    include: 'oauth'
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: localhost
      port: 27017
      database: getABeer
  redis:
    host: localhost
    port: 6379

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.underbell: DEBUG

springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      key-length: 256

jwt:
  secret-key: ThisIsSecretKeyForJWTForGetABeerREBUILDWithHS512SignatureAlgorithm
  access-token-expiration-minutes: 28800
  refresh-token-expiration-minutes: 1440